### ISSUE TITLE
Scope

### ISSUE THREAD

**Issue by newton-migosi** [nevilleomangi/lamport-clocks-web-workers#1]
https://github.com/nevilleomangi/lamport-clocks-web-workers/blob/286a954440a7ed8e2a5eb8b970d57869452dd4c4/main.js#L159

is variable still in scope?

**Comment by aphilas** [comment]
Yes, the constant on line 1: https://github.com/nevilleomangi/lamport-clocks-web-workers/blob/286a954440a7ed8e2a5eb8b970d57869452dd4c4/main.js#L1

**Comment by newton-migosi** [comment]
resolved
