### ISSUE TITLE
Object Property

### ISSUE THREAD

**Issue by newton-migosi** [nevilleomangi/lamport-clocks-web-workers#2]
https://github.com/nevilleomangi/lamport-clocks-web-workers/blob/286a954440a7ed8e2a5eb8b970d57869452dd4c4/main.js#L106

variable has no `id` property

**Comment by aphilas** [comment]
obj.prop = 'foo' either sets prop if exists, or creates it.

**Comment by newton-migosi** [comment]
sure does, asking for consistency
